# Generated by Django 4.2.7 on 2024-06-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tipoint_ticroix", "0003_remove_verifuser_pseudo"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConnected",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pseudo", models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
