# Generated by Django 4.2.7 on 2025-10-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tipoint_ticroix", "0005_game_delete_userconnected"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="bleu",
            field=models.BooleanField(default=True),
        ),
    ]
