# Generated by Django 4.2.7 on 2025-10-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tipoint_ticroix", "0006_game_bleu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="type",
            field=models.CharField(max_length=8),
        ),
    ]
