# Generated by Django 4.2.7 on 2025-10-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tipoint_ticroix", "0007_alter_game_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniqueVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
            ],
        ),
    ]
