name: Deploy Application

on:
  push:
    branches:
      - sprint8

     

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v2

    # - name: Set up Node.js (ou toute autre technologie si nécessaire)
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '14'

    # - name: Install dependencies
    #   run: npm install  # ou toute autre commande nécessaire pour installer les dépendances

    # - name: Build the project
    #   run: npm run build  # ou la commande nécessaire pour construire votre projet
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: List files
    #   run: pwd && sudo ls -la /home/runner/work/TipointTicroix/TipointTicroix

    - name: Deploy to server
      run: |

        # Donner toutes les permissions à un fichier
        chmod 777 tptcinit.sh

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit changes
      run: |
        git add tptcinit.sh
        git commit -m "Update permissions for tptcinit.sh" || echo "No changes to commit"

        - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utilisez le token d'accès
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/YERRO-Bruno/TipointTicroix.git
          git push origin HEAD:sprint8