name: Deploy Application

on:
  push:
    branches:
      - fullscreen 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Set up Node.js (ou toute autre technologie si nécessaire)
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '14'
    - name: Install dependencies
      run: npm install  

    - name: install foever
      run: npm install -g forever
  
    - name: Deploy to server
      run: chmod 755 tptcinit.sh
    - name: Deploy2 to server
      run: |
        chmod 755 /tipoint_ticroix/static/manifest
        chmod 755 /tipoint_ticroix/static/manifest/manifest.json
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    - name: Commit changes
      run: |
        git add tptcinit.sh
        if git commit -m "Update permissions for tptcinit.sh"; then
          echo "Changes committed."
        else
          echo "No changes to commit."
        fi
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utilisez le token d'accès
      run: |
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/YERRO-Bruno/TipointTicroix.git
        git push origin HEAD:fullscreen